name: release
on: [push]
env:
  JOURNAL_VERSION: "0.1.1"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: add-dependencies
        run: sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev systemd
      - name: build
        run: ./.github/scripts/build.sh
        shell: bash
      - name: build-artifacts
        run: ./.github/scripts/build-artifacts.sh
        shell: bash
